### ISSUE TITLE
Changing Vaadin class causes error

### ISSUE THREAD

**Issue by philippneugebauer** [ondrej-kvasnovsky/grails-vaadin-plugin#52]
When I change the vaadin class in `VaadinConfig.groovy` by 
```
mapping = ["/*": "de.ppn.UIManagement"]
```
I always recieve this error:

```
java.lang.ClassNotFoundException: de.ppn.UIManagement
	org.grails.plugins.tomcat.ParentDelegatingClassLoader.findClass(ParentDelegatingClassLoader.java:59)
	java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	com.vaadin.server.ServletPortletHelper.verifyUIClass(ServletPortletHelper.java:70)
	com.vaadin.server.ServletPortletHelper.initDefaultUIProvider(ServletPortletHelper.java:139)
	com.vaadin.server.VaadinService.createAndRegisterSession(VaadinService.java:768)
	com.vaadin.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:722)
	com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:663)
	com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:522)
	com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1400)
	com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305)
	com.vaadin.grails.server.DefaultServlet$_service_closure1.doCall(DefaultServlet.groovy:47)
	com.vaadin.grails.server.DefaultServlet.withNewSession(DefaultServlet.groovy:38)
	com.vaadin.grails.server.DefaultServlet.service(DefaultServlet.groovy:46)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	java.lang.Thread.run(Thread.java:745)
```

When I change everything back, it works, but it doesn't seem to be possible to change it.

**Comment by christoph-frick** [comment]
this class name is copied properly (e.g. in your IDE)?  the file is located in `src/(groovy|java)/de/ppn/UIManagement.(groovy|java)`?  the package in the file is `package de.ppn` and the classname is `UIManagement`?

**Comment by philippneugebauer** [comment]
What does "copied properly" mean? I have created a new groovy class.

Yes, the file is located in src/groovy/de/ppn/UIManagement.groovy and your guesses are correct

**Comment by christoph-frick** [comment]
i mean by "copy reference" and then paste or alike.  i just want to make sure, that this is not just a trivial typo.  please add all the more relevant informations: grails version, vaadin version, when does it happen (grails run-app?), etc... and what do you mean "change it back".  what is working there?  and your class there extends vaadin's UI?

**Comment by philippneugebauer** [comment]
The package name must be right because it works for the other class. To ensure the absence of typos, I copied the class name from the renaming menu.

I'm using grails 2.4.4 and this plugin in version 7.3.9. It happens at `grails run-app` after I try to visit the site. I recieve then the error posted above and the app crashes.

What I meant with "change it back" is that after I changed the class in the `VaadinConfig.groovy` manually to another, it does not work. As I encountered so far, it does not crash, if I use the first specific class (`MyUI.groovy`) and rename it by the refactoring menu, so I guess there must be somewhere else anything changed as well.

**Comment by christoph-frick** [comment]
please provide a failing example or check my working version here https://github.com/christoph-frick/grails-vaadin-issue-52

**Comment by philippneugebauer** [comment]
hm, with your example and a first try I couldn't reproduce the problem. I will do some further investigation, but it can take some time, maybe till easter

**Comment by christoph-frick** [comment]
@ondrej-kvasnovsky i think you should close this ticket

**Comment by philippneugebauer** [comment]
I'm sorry for the delay.

Actually, I could reproduce my error, but just when the names of the classes or files weren't the same. Therefore, I think that I had a typo mistake. Furthermore, I couldn't find any difference in the configs.

I have uploaded my tries here, so that you can have a look as well:
https://github.com/philippneugebauer/grails-vaadin-issue-52

**Comment by christoph-frick** [comment]
@philippneugebauer the example fails, because there is no class with the name in the mapping.

**Comment by philippneugebauer** [comment]
It worked and the last commit was just for the visualization of non critical config differences. I have overlooked the difference in the mapping, but as I said it doesn't matter. 

Therefore, I think as well you should close the issue because there is a high probability that I did a mistake that I overlooked when I reported the issue.
