### ISSUE TITLE
grails 3.0 Support

### ISSUE THREAD

**Issue by jamroks** [ondrej-kvasnovsky/grails-vaadin-plugin#53]
Hi,

Appologie if this is not the place to ask the question, but i'm wondering if the plugin is compatible with grails 3.0 ? if not , is it going to get out soon ? 

I'm asking becuse i'm starting a new project and we have two choice :  
- grails + vaadin 
  or 
- Spring boot + vaadin 

But since grails 3.0 is built on springboot we could have the best of both world by using directly grails 3.0 :  grails+ (springBoot under the hood) +vaadin

**Comment by ondrej-kvasnovsky** [comment]
Hi, I will look at it. I will let you know here, whether Grails 3 is supported.

**Comment by christoph-frick** [comment]
this plugin will not work without changing it.

**Comment by ondrej-kvasnovsky** [comment]
Just an update. I am working on this. "Only" widgetset and SASS compilation are missing.

**Comment by zhuravskiy** [comment]
Grails .3.0 support gradle, and gradle plugins, i dont try, but i suppose, you can use vaadin plugin for gradle, for example https://github.com/johndevs/gradle-vaadin-plugin

**Comment by christoph-frick** [comment]
if you can pull any inspiration out of this - it's wiring the gradle-vaadin-plugin with springboot (https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/gradle/springboot-vaadin-fixes.gradle)

**Comment by jamroks** [comment]
Very interesting suggestion , i will looking into the combo Springboot+vaadin+gradle+groovy

Thanks a lot  Ondrej , i'll can't to test it out soon as it's ready

**Comment by paulorcf** [comment]
+1

**Comment by m4ver1k** [comment]
+1

@ondrej-kvasnovsky  Thanks a lot for the plugin. About to start a new project with Grails and Vaadin,
 How soon can we expect the Grails 3 Compatible version of plugin ?

**Comment by ondrej-kvasnovsky** [comment]
I have finished first version of plugin, it is grails3 branch. I am about to do several tests and release it.

**Comment by bassmartin** [comment]
How is the testing going? Is there going to be a release soon?

**Comment by iriusrisk** [comment]
Thank you @ondrej-kvasnovsky for this plugin!  Any update on the grails 3 status?

**Comment by ondrej-kvasnovsky** [comment]
I am releasing the plugin and testing it nowadays. There are some issues, so it takes time.

**Comment by ondrej-kvasnovsky** [comment]
Plugin for Grails 3 is released and I am working on few tutorials how to create project and how to do basic stuff in the new plugin. I will post these tutorials here and then close this issue.

**Comment by cosmocracy** [comment]
Need to decide whether to put some energy behind using Vaadin + Grails3... Wondering if this is stalled or if there are some good examples to follow.  I'd be happy to help collaborate on a tutorial if there are enough examples available.

**Comment by ondrej-kvasnovsky** [comment]
@cosmocracy I made working version of plugin for Grails 3 but never got to publish a tutorial (yes, I know, I should do that). I am planning to come back to this plugin new few weeks, update dependencies and release a new version. Then we can elaborate on a tutorial, every help is greatly appreciated.

**Comment by ondrej-kvasnovsky** [comment]
Here is the tutorial how to get the plugin working with Grails 3.2.8 and Vaadin 7.7.8: 

Download and setup Grails: 
```
GRAILS_HOME=/Users/ondrej/Documents/Libraries/grails-3.2.8
export GRAILS_HOME
export PATH=$PATH:$GRAILS_HOME/bin
```

Create new Grails application: 
```
grails create app sample-project
cd sample-project
```

Open build.gradle and add build plugin: 
```
buildscript {
    repositories {
        // ... other repos...
        maven { url 'https://dl.bintray.com/ondrej-kvasnovsky/plugins/' } // ADD THIS
    }
    dependencies {
        // ... keep the other plugins for now... 
        classpath 'com.vaadinongrails:vaadin-gradle-plugin:1.0.9' // ADD THIS
    }
}

apply plugin: 'com.vaadinongrails.vaadin-gradle-plugin' // ADD THIS
```

You can get latest version of that plugin from: https://bintray.com/ondrej-kvasnovsky/plugins/vaadin-gradle-plugin 

Then add compile dependency in build.gradle: 
```
repositories {
    // ... other repos...
    maven { url 'https://dl.bintray.com/ondrej-kvasnovsky/plugins' } // ADD THIS
}
dependencies {
    // keep other dependencies as they are (for now)
    compile 'com.vaadinongrails:grails-vaadin-plugin:1.0.11' // ADD THIS
}
```

Explore what tasks has been added by 'vaadin-gradle-plugin':
```
gradle tasks
```
You should see these in your tasks: 
```
...
Vaadin tasks
------------
vaadin-compile-sass - Compiles SASS and into CSS.
vaadin-compile-widgetset - Compiles Vaadin Addons and components into Javascript.
vaadin-quickstart
vaadin-spring-quickstart
...
```

Now you can choose if you want to use Spring or not. If you want to use Spring in your app, run: 
```
gradle vaadin-spring-quickstart
```
It adds all support files you need to develop and run your application with Spring. 

If you choose to develop app without Spring,  run this one: 
```
gradle vaadin-quickstart
```

Now you are ready to run the app: 
```
gradle bootRun
```

Please let me know if this works for you guys.

**Comment by phillipjohnson** [comment]
Hi @ondrej-kvasnovsky, that was a great start! I was able to get a very simple UI running in grails.

Some more guidance on views would be appreciated. In a "standard" Spring Vaadin app, the views register automatically based on name and I use the navigator. But you cannot specify a name with the `VaadinView` annotation, Looking at some of the demos in this repo, it looks like the preferred method is to use `Views.enter`, but that is giving `IllegalArgumentException: No View found for type`.

Also, any idea on compatibility with Vaadin 8?

**Comment by wehe64** [comment]
Thanks @ondrej-kvasnovsky for the update of the plugin and for that fine write-up!

I've now successfully run a groovy-vied version of the Vaadin Getting-Started Tutorial (customer list & form) using Gorm/H2 - as far as I can see the plugin works really well! 

In VlaadinConfig, the openSessionInViewFilter needs to use hibernate5 for Grom to work though.

And your write-up should IMHO go on the plugin's page at plugins.grails.org as well, it would be very helpfull there.

Thanks a lot again, I'm declaring you my hero of the week =:-)
Cheers, weHe

**Comment by ondrej-kvasnovsky** [comment]
Thanks for feedback, I will look at it. I am going to close this issue and we can continue with other issues if you find anything.

Vaadin 8 support is under this issue: #62.

**Comment by cosmocracy** [comment]
Nice work, thank you for this. I'm personally excited to see how well Vaadin team up with the large ecosystem of goodies in Grails3!
