### ISSUE TITLE
sass compilation fails (wrong repository urls)

### ISSUE THREAD

**Issue by Meyenhofer** [ondrej-kvasnovsky/grails-vaadin-plugin#55]
when trying to compile a production war, the sass compilation fails.

[get] Getting: http://vaadin.com/download/release/7.3/groovy.util.ConfigObject@500beb9f/vaadin-all-groovy.util.ConfigObject@500beb9f.zip
      [get] To: C:\Users\meyenhof\Desktop\slim\vaadin-sass-temp\vaadin-all-groovy.util.ConfigObject@500beb9f.zip
      [get] Error opening connection java.io.FileNotFoundException: http://vaadin.com/download/release/7.3/groovy.util.ConfigObject@500beb9f/vaadin-all-groovy.util.ConfigObject@500beb9f.zip
      [get] Error opening connection java.io.FileNotFoundException: http://vaadin.com/download/release/7.3/groovy.util.ConfigObject@500beb9f/vaadin-all-groovy.util.ConfigObject@500beb9f.zip
      [get] Error opening connection java.io.FileNotFoundException: http://vaadin.com/download/release/7.3/groovy.util.ConfigObject@500beb9f/vaadin-all-groovy.util.ConfigObject@500beb9f.zip
      [get] Can't get http://vaadin.com/download/release/7.3/groovy.util.ConfigObject@500beb9f/vaadin-all-groovy.util.ConfigObject@500beb9f.zip to C:\Users\meyenhof\Desktop\slim\vaadin-sass-temp\vaadin-all-groovy.util.ConfigObject@500beb9f.zip
.     [echo] SASS compilation: Failed

The url's seem to point to nowhere.

**Comment by christoph-frick** [comment]
dupliate of #54 ?

**Comment by Meyenhofer** [comment]
I am not sure.
Thing is that http://vaadin.com/download/release/7.3/ exists, but anything that comes after that seems to point to a non-existing location

**Comment by ondrej-kvasnovsky** [comment]
Can you share your VaadinConfig.groovy please?

**Comment by Meyenhofer** [comment]
vaadin {

    // Your Vaadin UI classes that extends com.vaadin.ui.UI.
    // The application will be available at e.g. http://localhost:8080/grails-vaadin7-demo/
    mapping = [
            "/*": "app.SlimUi"
    ]

    // Extra mapping in case you need 'reserve' a URL and it shouldn't be mapped to e.g. /* by Vaadin
    // mappingExtras = [
    //         '/console/*'
    // ]

    // This is optional because the servlet is provided by default.
    // servletClass = "com.mycompany.MyGrailsAwareApplicationServlet"

    productionMode = false

    // Uncomment this to enable asynchronous communication, useful for vaadin-push
    // asyncSupported = true

    // Uncomment and provide name of the theme (a directory name in web-app/VAADIN/themes folder)
    themes = ['unifr_sci']
    // You can specify exact version of Vaadin for SASS compilation
    // sassCompile = '7.1.9'

    // Use your own widgetset (e.g. include addons)
    // - add the depedencies in BuildConfig.groovy
    // - create src/java/com/mycompany/widgetset.gwt.xml 
    //   and add the widgetset from the addon there
    // - run ``grails vaadin-compile-widgetset`` afterwards 
    //   (and after major Vaadin version changes)
    // Unless set the default from Vaadin is used
    // widgetset = 'com.mycompany.widgetset'

    compile {
        //usePathJar = true //if you have problem with long classpath and vaadin-compile-widgetset on windows, uncomment this line
        //classPathRegExp="(?ismx)([^;]*(vaadin|gwt-dev|ant|sac)[^;]*);" //Regex pattern including jar contains following words vaadin|gwt-dev|ant|sac, used by default for path jar

        //memory settings
        //antMaxMemory='512m'
        //gwtCompilerXss='1024k'

        //workers=4 //by default 4 parallel workers threads used for compile
    }
}

environments {
    production {
        vaadin {
            productionMode = true
        }
    }
}

**Comment by ondrej-kvasnovsky** [comment]
Can you verify the fix using compile ":vaadin:7.4.7" ?

https://twitter.com/grailsplugins/status/603758590999056384

**Comment by Meyenhofer** [comment]
that worked.
with: 
grails clean-all
grails war
grails prod war

(it wouldn't take grails prod war directly)
thanks to both Ondrej's
