### ISSUE TITLE
Failed to resolve dependencies 

### ISSUE THREAD

**Issue by Chillwabbitt** [ondrej-kvasnovsky/grails-vaadin-plugin#56]
I added the plugin to a Grails 2.2.5 project

//BuildConfig.groovy
compile ":vaadin:7.4.7"

I'm getting the following error
Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):
- org.eclipse.jetty.orbit:javax.transaction:1.1.1.v201105210645
- org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016
- org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020
- org.eclipse.jetty.orbit:javax.activation:1.1.0.v201105071233
- org.eclipse.jetty.orbit:javax.annotation:1.1.0.v201108011116
- org.eclipse.jetty.orbit:org.objectweb.asm:3.1.0.v200803061910

Any ideas?

**Comment by christoph-frick** [comment]
at least the first dep is on maven central.  what is the "history" of your config?  have you updated to this vaadin version (from which)? do other plugins resolve properly?  is your BuildConfig setup properly to read maven central/jcenter? can problems with proxies etc be ruled out?

**Comment by Chillwabbitt** [comment]
Sorry for the late reply, I've been quite busy.
So here's a crazy one for you. If I create a new project using Grails 2.4.5, no issues but if I try with an older version like above Grails 2.2.5 then I have this issue.

**Comment by ondrej-kvasnovsky** [comment]
These old Grails versions... Can you run: https://grails.github.io/grails-doc/latest/ref/Command%20Line/dependency-report.html with 2.2.5 and with 2.4.5 and post it here using https://www.diffchecker.com? Or you have migrated to 2.4.5 and you do not care anymore?

**Comment by Chillwabbitt** [comment]
I'll happily post the report. 2.2.5 generates a html report and 2.4.5 has a command line output report. Any ideas on how to get the 2.2.5 to output the same type of report?

I have done the upgrade, so I think this might just be an informative thing for someone else.

**Comment by ondrej-kvasnovsky** [comment]
Not clear what should be done by the plugin here. There are other dependency issues (that might be probably solved with Grails 3, Gradle).
