### ISSUE TITLE
Control dependency on plugin

### ISSUE THREAD

**Issue by aluismarte** [ondrej-kvasnovsky/grails-vaadin-plugin#57]
Plugin Grails 3

The plugin is too big and load a version of vaadin internal.
Delete dependency on old grails.

**Comment by ondrej-kvasnovsky** [comment]
You are absolutely right. I will do that.

**Comment by ondrej-kvasnovsky** [comment]
I cleaned dependencies in 1.0.6 version: https://bintray.com/ondrej-kvasnovsky/plugins/grails-vaadin-plugin/1.0.6 

Anyway, I appreciate you tried the new plugin and you were able to get it working. I am working on some tutorials how to create a new project in Grails 3.

**Comment by aluismarte** [comment]
OK, good! i will test and on next week i write a mini how to on my blog "Grails 3.1 and Vaadin "
