### ISSUE TITLE
Grails 3 demo project references an unreleased grade plugin version

### ISSUE THREAD

**Issue by bassmartin** [ondrej-kvasnovsky/grails-vaadin-plugin#59]
The demo Grails 3 demo project references `classpath 'com.vaadinongrails:vaadin-gradle-plugin:1.0.7'` but version `1.0.7` is not released in `https://dl.bintray.com/ondrej-kvasnovsky/plugins/com/vaadinongrails/vaadin-gradle-plugin/`. The latest version available is `1.0.5`

**Comment by ondrej-kvasnovsky** [comment]
Hi, I am sorry about that, please use the latest versions from https://bintray.com/ondrej-kvasnovsky/plugins
