### ISSUE TITLE
Grails Vaadin plugin is trying to download an unavailable sources-jar

### ISSUE THREAD

**Issue by bassmartin** [ondrej-kvasnovsky/grails-vaadin-plugin#60]
The Grails Vaadin plugin is trying tu pull the sources jar of the `validation-api`. It cannot be find in the regular Grails public repository neither in the `ondrej-kvasnovsky` repository.
Moreover, I don't think sources jar should be listed as dependencies in the plugin

`Error:Could not find validation-api-sources.jar (javax.validation:validation-api:1.1.0.Final).`

**Comment by bassmartin** [comment]
Workaround is to exclude it for the moment:

```
    compile('com.vaadinongrails:grails-vaadin-plugin:1.0.8') {
        exclude module: 'validation-api'
    }
```

**Comment by ondrej-kvasnovsky** [comment]
Hi Martin, 

What is the plugin version you are using?

**Comment by bassmartin** [comment]
1.0.8

**Comment by wehe64** [comment]
Hello Onrej, same here: including the plugin in Grails 3.2.5 fails.
`compile "org.grails.plugins:vaadin:7.6.1" `  in build.gradle leads to:
```
A problem occurred configuring root project 'my-app'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not find validation-api-sources.jar (javax.validation:validation-api:1.1.0.Final).
```
is the validation-api needed for the plugin?
and thank you for the plugin! weHe

**Comment by wehe64** [comment]
@bassmartin: same with com.vaadinongrails:grails-vaadin-plugin:1.0.8
but you can download the missing files manually from
http://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/
and put them into your local maven cache at
~/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final-sources.jar
that worked well for me.
hth! weHe

**Comment by christoph-frick** [comment]
without the conext of the whole problem, i'd assume, that this error is due to the compilation of the widgetset.  where the GWT/closure compiler needs the sources.  but vaadin's version of the GWT compiler is "old" and needs 1.0 while 1.1 is pulled in as a transitive dep (most likely from spring-boot-starter etc).

**Comment by wehe64** [comment]
FYI, just for curiosity I went through the same process on a different machine:

1. installed grails 3.2.5 using sdkman
1. set up a new project
1. added `compile 'com.vaadinongrails:grails-vaadin-plugin:1.0.8'` 
to build.grade (without the exclude)

and it all went through without any problem.
HTH!

**Comment by ondrej-kvasnovsky** [comment]
I have tested the behavior with the latest versions from https://bintray.com/ondrej-kvasnovsky/plugins and didn't face this issue (using latest version of Grails: 3.2.8 and latest Vaadin 7.7.8). Please reopen if the issue occurs again.
