### ISSUE TITLE
Can it support vaddin 10?

### ISSUE THREAD

**Issue by hanyou** [ondrej-kvasnovsky/grails-vaadin-plugin#65]
Can it support vaddin 10?

**Comment by ondrej-kvasnovsky** [comment]
I think it can. We just need to update dependencies and do couple of tests.

**Comment by ondrej-kvasnovsky** [comment]
I just tried to upgrade Vaadin version to 10.0.6 and that would require more time. If anyone is willing to cooperate, I will absolutely help with it. I just need to know how much interest there is to get this plugin working with Vaadin 10.

**Comment by ondrej-kvasnovsky** [comment]
I think you should really consider using Spring Boot instead of Grails (check this out: https://spring.io/guides/gs/crud-with-vaadin)
